version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

submodules:
  include:
    - PVGeo
  recursive: true

python:
   version: 3
   install:
   - requirements: ./requirements.txt

sphinx:
  configuration: ./conf.py
  builder: html
  fail_on_warning: false
